# Generated by Django 6.1.1 on 2026-09-11 15:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquacare', '0002_alter_alert_id_alter_alertacknowledgement_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseRiskPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(db_index=True, max_length=100)),
                ('prediction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('risk_score', models.FloatField(help_text='Calculated continuous risk score (0.0 to 100.0)')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk (0-30)'), ('MEDIUM', 'Medium Risk (31-60)'), ('HIGH', 'High Risk (61-80)'), ('CRITICAL', 'Critical Outbreak Risk (81-100)')], default='LOW', max_length=20)),
                ('outbreak_probability', models.FloatField(default=0.0, help_text='Predicted statistical probability of an outbreak within next 14 days (0.0 to 1.0)')),
                ('predicted_disease', models.CharField(blank=True, help_text='Most probable water-borne pathogen (e.g. Diarrhea, Cholera, Typhoid)', max_length=100, null=True)),
                ('contributing_factors', models.JSONField(default=dict)),
                ('plain_language_explanation', models.TextField(blank=True, null=True)),
                ('recommended_actions', models.JSONField(default=list)),
                ('model_name', models.CharField(default='Disease-Ensemble-v1', max_length=100)),
                ('is_latest', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Disease Risk Prediction',
                'verbose_name_plural': 'Disease Risk Predictions',
                'ordering': ['-prediction_date'],
            },
        ),
        migrations.RenameModel(
            old_name='RiskPrediction',
            new_name='WaterRiskPrediction',
        ),
        migrations.AlterModelOptions(
            name='waterriskprediction',
            options={'ordering': ['-prediction_date'], 'verbose_name': 'Water Risk Prediction / Early Warning', 'verbose_name_plural': 'Water Risk Predictions & Early Warnings'},
        ),
        migrations.RemoveField(
            model_name='waterriskprediction',
            name='outbreak_probability',
        ),
        migrations.RemoveField(
            model_name='waterriskprediction',
            name='predicted_disease',
        ),
        migrations.AlterField(
            model_name='waterriskprediction',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_risk_predictions', to='aquacare.village'),
        ),
        migrations.RemoveIndex(
            model_name='waterriskprediction',
            name='aquacare_ri_village_3650cb_idx',
        ),
        migrations.RemoveIndex(
            model_name='waterriskprediction',
            name='aquacare_ri_risk_le_2a5021_idx',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='related_prediction',
            new_name='related_water_prediction',
        ),
        migrations.RemoveIndex(
            model_name='village',
            name='aquacare_vi_risk_le_6c8acb_idx',
        ),
        migrations.AddIndex(
            model_name='diseaseriskprediction',
            index=models.Index(fields=['district', 'is_latest'], name='aquacare_di_distric_1d0b8d_idx'),
        ),
        migrations.AddIndex(
            model_name='diseaseriskprediction',
            index=models.Index(fields=['risk_level'], name='aquacare_di_risk_le_b32750_idx'),
        ),
        migrations.AddField(
            model_name='alert',
            name='related_disease_prediction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_alerts', to='aquacare.diseaseriskprediction'),
        ),

        migrations.RemoveField(
            model_name='village',
            name='risk_level',
        ),
        migrations.RemoveField(
            model_name='village',
            name='risk_score',
        ),
        migrations.AddIndex(
            model_name='waterriskprediction',
            index=models.Index(fields=['village', 'is_latest'], name='aquacare_wa_village_952707_idx'),
        ),
        migrations.AddIndex(
            model_name='waterriskprediction',
            index=models.Index(fields=['risk_level'], name='aquacare_wa_risk_le_72fc87_idx'),
        ),

    ]
