# Generated by Django 5.2.11 on 2026-09-09 04:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Short alert headline (e.g. 'Boil Water Advisory: North Well #2')", max_length=200)),
                ('message', models.TextField(help_text='Detailed alert text and instructions')),
                ('severity', models.CharField(choices=[('INFO', 'Informational Notice'), ('WARNING', 'Warning / Caution'), ('HIGH', 'High Alert'), ('CRITICAL', 'Critical Emergency')], default='WARNING', max_length=15)),
                ('alert_type', models.CharField(choices=[('OUTBREAK_WARNING', 'Disease Outbreak Warning'), ('WATER_CONTAMINATION', 'Water Contamination Detected'), ('CASE_SPIKE', 'Unusual Health Case Spike'), ('BOIL_WATER_ADVISORY', 'Boil Water Advisory'), ('WEATHER_EVENT', 'Flood / Heavy Rainfall Risk'), ('MAINTENANCE', 'Water Supply Maintenance')], default='OUTBREAK_WARNING', max_length=30)),
                ('target_audience', models.CharField(choices=[('ALL', 'All Users (Community, Health Workers, Authority)'), ('COMMUNITY', 'Community / Citizens Only'), ('HEALTH_WORKER', 'Health Workers Only'), ('AUTHORITY', 'Health Authorities Only')], default='ALL', max_length=20)),
                ('action_required', models.TextField(blank=True, help_text='Recommended immediate actions for citizens or field workers', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Active alerts display banner and warnings in the portals')),
                ('generated_by_ai', models.BooleanField(default=False, help_text='True if automatically generated by ML Risk Prediction threshold breach')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Alert & Advisory',
                'verbose_name_plural': 'Alerts & Advisories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskPrediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('risk_score', models.FloatField(help_text='Calculated continuous risk score (0.0 to 100.0)')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk (0-30)'), ('MEDIUM', 'Medium Risk (31-60)'), ('HIGH', 'High Risk (61-80)'), ('CRITICAL', 'Critical Outbreak Risk (81-100)')], default='LOW', max_length=20)),
                ('outbreak_probability', models.FloatField(default=0.0, help_text='Predicted statistical probability of an outbreak within next 14 days (0.0 to 1.0)')),
                ('predicted_disease', models.CharField(blank=True, help_text='Most probable water-borne pathogen (e.g. Diarrhea, Cholera, Typhoid)', max_length=100, null=True)),
                ('contributing_factors', models.JSONField(default=dict, help_text="Feature impact breakdown: {'water_contamination': 45, 'case_surge': 30, 'temperature': 15, 'rainfall': 10}")),
                ('plain_language_explanation', models.TextField(blank=True, help_text='Non-technical explanation for community citizens', null=True)),
                ('recommended_actions', models.JSONField(default=list, help_text="List of actionable recommendations (e.g. ['Boil water before consumption', 'Chlorinate Community Well #1'])")),
                ('model_name', models.CharField(default='WaterBorne-Ensemble-v1', help_text='Identifier of the ML algorithm/version used', max_length=100)),
                ('is_latest', models.BooleanField(default=True, help_text='Flag indicating this is the most current prediction for the village')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Risk Prediction / Early Warning',
                'verbose_name_plural': 'Risk Predictions & Early Warnings',
                'ordering': ['-prediction_date'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('COMMUNITY', 'Community User / Citizen'), ('HEALTH_WORKER', 'Health Worker'), ('AUTHORITY', 'Health Authority / Admin')], default='COMMUNITY', help_text='Role determining user permissions and available portal interface', max_length=20)),
                ('phone', models.CharField(blank=True, help_text='Contact telephone number', max_length=15, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('organization', models.CharField(blank=True, help_text='Primary Health Centre (PHC), District Hospital, or Administrative department', max_length=200, null=True)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi')], default='en', help_text='Preferred language for UI and advisory notifications', max_length=10)),
                ('notification_alerts', models.BooleanField(default=True, help_text='Receive critical health warnings and boil-water advisories')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AlertAcknowledgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='aquacare.alert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_acknowledgements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alert Acknowledgement',
                'verbose_name_plural': 'Alert Acknowledgements',
                'unique_together': {('alert', 'user')},
            },
        ),
        migrations.AddField(
            model_name='alert',
            name='acknowledged_users',
            field=models.ManyToManyField(blank=True, related_name='acknowledged_alerts', through='aquacare.AlertAcknowledgement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='related_prediction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_alerts', to='aquacare.riskprediction'),
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Village or locality name', max_length=150)),
                ('code', models.CharField(help_text='Census / administrative village code', max_length=50, unique=True)),
                ('district', models.CharField(max_length=100)),
                ('block', models.CharField(blank=True, help_text='Sub-district / Block / Tehsil', max_length=100, null=True)),
                ('state', models.CharField(default='State', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude in decimal degrees (e.g. 26.8467)', max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude in decimal degrees (e.g. 80.9462)', max_digits=9)),
                ('population', models.PositiveIntegerField(default=1000, help_text='Estimated resident population')),
                ('household_count', models.PositiveIntegerField(default=200, help_text='Total number of households')),
                ('primary_water_source', models.CharField(blank=True, default='Borewell', help_text='Primary drinking water source (e.g. Borewell, River, Municipal Tap, Handpump)', max_length=100)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('CRITICAL', 'Critical Outbreak Risk')], default='LOW', help_text='Current aggregated disease outbreak risk level', max_length=20)),
                ('risk_score', models.FloatField(default=0.0, help_text='Current ML calculated risk score from 0.0 (safest) to 100.0 (highest risk)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Village',
                'verbose_name_plural': 'Villages',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['district', 'name'], name='aquacare_vi_distric_a08f05_idx'), models.Index(fields=['risk_level'], name='aquacare_vi_risk_le_6c8acb_idx')],
            },
        ),
        migrations.AddField(
            model_name='riskprediction',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_predictions', to='aquacare.village'),
        ),
        migrations.AddField(
            model_name='alert',
            name='village',
            field=models.ForeignKey(help_text='Village where alert applies', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='aquacare.village'),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_villages',
            field=models.ManyToManyField(blank=True, help_text='Villages assigned to this Health Worker for field surveillance', related_name='health_workers', to='aquacare.village'),
        ),
        migrations.AddField(
            model_name='user',
            name='village',
            field=models.ForeignKey(blank=True, help_text='Primary residential village for Community Users', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='aquacare.village'),
        ),
        migrations.CreateModel(
            name='WaterSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Identifier (e.g. 'Community Handpump #3', 'North Well')", max_length=150)),
                ('source_type', models.CharField(choices=[('WELL', 'Open Well'), ('TUBEWELL', 'Tube Well / Borewell'), ('HANDPUMP', 'Hand Pump'), ('RIVER', 'River / Stream / Canal'), ('TAP', 'Piped / Tap Water Supply'), ('POND', 'Pond / Tank / Lake'), ('OTHER', 'Other Water Source')], default='HANDPUMP', max_length=20)),
                ('status', models.CharField(choices=[('SAFE', 'Safe / Potable'), ('MODERATE', 'Moderate Risk'), ('CONTAMINATED', 'Contaminated / Unsafe'), ('UNDER_TREATMENT', 'Under Treatment / Chlorination'), ('INACTIVE', 'Inactive / Broken / Dry')], default='SAFE', help_text='Current operational and safety status', max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Precise GPS latitude of the water point', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Precise GPS longitude of the water point', max_digits=9, null=True)),
                ('is_public', models.BooleanField(default=True, help_text='Whether this water source is accessible for public community use')),
                ('depth_meters', models.FloatField(blank=True, help_text='Well/borewell depth in meters', null=True)),
                ('installed_year', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('village', models.ForeignKey(help_text='Village where this water source is situated', on_delete=django.db.models.deletion.CASCADE, related_name='water_sources', to='aquacare.village')),
            ],
            options={
                'verbose_name': 'Water Source',
                'verbose_name_plural': 'Water Sources',
                'ordering': ['village', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WaterQualityTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when sample was collected')),
                ('ph', models.FloatField(help_text='pH value (Standard safe range: 6.5 to 8.5)')),
                ('turbidity', models.FloatField(help_text='Turbidity in NTU (Standard safe: < 5.0 NTU, ideal < 1.0)')),
                ('tds', models.FloatField(help_text='Total Dissolved Solids in mg/L or ppm (Standard safe: < 500 mg/L)')),
                ('temperature', models.FloatField(help_text='Water temperature in °C')),
                ('coliform_bacteria', models.FloatField(default=0.0, help_text='Total Coliform count (CFU/100mL or MPN/100mL, standard is 0)')),
                ('e_coli_detected', models.BooleanField(default=False, help_text='Whether pathogenic Escherichia coli was detected in sample')),
                ('chlorine_residual', models.FloatField(blank=True, help_text='Residual free chlorine in mg/L (Standard: 0.2 - 0.5 mg/L)', null=True)),
                ('dissolved_oxygen', models.FloatField(blank=True, help_text='Dissolved Oxygen (DO) in mg/L', null=True)),
                ('nitrate', models.FloatField(blank=True, help_text='Nitrate concentration in mg/L (Safe: < 45 mg/L)', null=True)),
                ('wqi', models.FloatField(blank=True, help_text='Water Quality Index score from 0 (heavily polluted) to 100 (pristine)', null=True)),
                ('status', models.CharField(choices=[('EXCELLENT', 'Excellent (WQI >= 90)'), ('GOOD', 'Good / Safe (70 <= WQI < 90)'), ('POOR', 'Poor / Caution (50 <= WQI < 70)'), ('VERY_POOR', 'Very Poor / High Risk (25 <= WQI < 50)'), ('UNSAFE', 'Unsafe / Critical Contamination (WQI < 25)')], default='GOOD', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Field notes, odor, color, or sampling observations', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tested_by', models.ForeignKey(blank=True, help_text='Health Worker or Lab Technician who conducted the sample test', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_water_tests', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_quality_tests', to='aquacare.village')),
                ('water_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_tests', to='aquacare.watersource')),
            ],
            options={
                'verbose_name': 'Water Quality Test',
                'verbose_name_plural': 'Water Quality Tests',
                'ordering': ['-sample_date'],
            },
        ),
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_identifier', models.CharField(blank=True, help_text='Anonymized ID / token for patient privacy (e.g. PT-2026-0041)', max_length=50)),
                ('patient_name', models.CharField(blank=True, max_length=120, null=True)),
                ('age', models.PositiveIntegerField(help_text='Patient age in years')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=10)),
                ('disease_type', models.CharField(choices=[('CHOLERA', 'Cholera'), ('TYPHOID', 'Typhoid Fever'), ('ACUTE_DIARRHEA', 'Acute Diarrhea'), ('DYSENTERY', 'Dysentery'), ('HEPATITIS_A', 'Hepatitis A'), ('HEPATITIS_E', 'Hepatitis E'), ('GASTROENTERITIS', 'Gastroenteritis'), ('OTHER', 'Other Water-Borne Disease')], default='ACUTE_DIARRHEA', max_length=30)),
                ('symptoms', models.JSONField(default=list, help_text="List of observed symptoms (e.g. ['Diarrhea', 'Vomiting', 'Dehydration', 'High Fever'])")),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('CRITICAL', 'Critical / ICU Required')], default='MODERATE', max_length=15)),
                ('status', models.CharField(choices=[('UNDER_TREATMENT', 'Under Treatment'), ('RECOVERED', 'Recovered'), ('HOSPITALIZED', 'Hospitalized / Referred'), ('DECEASED', 'Deceased')], default='UNDER_TREATMENT', max_length=20)),
                ('date_of_onset', models.DateField(help_text='Date when symptoms first started')),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when case was logged')),
                ('treatment_administered', models.TextField(blank=True, help_text='Treatment given (e.g. Oral Rehydration Salts, Antibiotics, Zinc, IV Infusion)', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Health Worker logging this clinical record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_cases', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(help_text='Village where the patient resides or contracted the illness', on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='aquacare.village')),
                ('suspected_water_source', models.ForeignKey(blank=True, help_text='Suspected contaminated water point consumed by the patient', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_cases', to='aquacare.watersource')),
            ],
            options={
                'verbose_name': 'Health Surveillance Record',
                'verbose_name_plural': 'Health Surveillance Records',
                'ordering': ['-date_recorded'],
            },
        ),
        migrations.CreateModel(
            name='CommunityReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('reporter_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('symptoms', models.JSONField(default=list, help_text="Selectable symptom chips (e.g. ['Diarrhea', 'Vomiting', 'Stomach Pain', 'High Fever'])")),
                ('people_affected', models.PositiveIntegerField(default=1, help_text='Number of household or community members experiencing these symptoms')),
                ('age_group', models.CharField(choices=[('CHILD', 'Children (< 12 yrs)'), ('TEEN', 'Teenagers (12-18 yrs)'), ('ADULT', 'Adults (18-60 yrs)'), ('ELDERLY', 'Senior Citizens (60+ yrs)'), ('ALL_AGES', 'Multiple / All Age Groups')], default='ADULT', max_length=15)),
                ('water_issue_observed', models.CharField(blank=True, help_text="e.g. 'Foul smell', 'Cloudy muddy water', 'Unusual taste'", max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='Additional observations or context provided by the citizen', null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review by Health Worker'), ('VERIFIED', 'Verified / Confirmed Outbreak'), ('ACTION_TAKEN', 'Action Taken / Treated'), ('RESOLVED', 'Resolved'), ('DISMISSED', 'Dismissed / False Alarm')], default='SUBMITTED', max_length=20)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(blank=True, help_text='Registered Community User reporting the issue (null if reported anonymously)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='community_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Health Worker or Authority who inspected the report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_citizen_reports', to=settings.AUTH_USER_MODEL)),
                ('village', models.ForeignKey(help_text='Village where the health issue occurred', on_delete=django.db.models.deletion.CASCADE, related_name='community_reports', to='aquacare.village')),
                ('water_source_suspected', models.ForeignKey(blank=True, help_text='Suspected contaminated well/handpump/tap', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aquacare.watersource')),
            ],
            options={
                'verbose_name': 'Community Health Report',
                'verbose_name_plural': 'Community Health Reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='riskprediction',
            index=models.Index(fields=['village', 'is_latest'], name='aquacare_ri_village_3650cb_idx'),
        ),
        migrations.AddIndex(
            model_name='riskprediction',
            index=models.Index(fields=['risk_level'], name='aquacare_ri_risk_le_2a5021_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['village', 'is_active'], name='aquacare_al_village_453a00_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity'], name='aquacare_al_severit_62e2d7_idx'),
        ),
        migrations.AddIndex(
            model_name='waterqualitytest',
            index=models.Index(fields=['village', '-sample_date'], name='aquacare_wa_village_d9fd65_idx'),
        ),
        migrations.AddIndex(
            model_name='waterqualitytest',
            index=models.Index(fields=['status'], name='aquacare_wa_status_5c152a_idx'),
        ),
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['village', '-date_recorded'], name='aquacare_he_village_0f243f_idx'),
        ),
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['disease_type'], name='aquacare_he_disease_c0959b_idx'),
        ),
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['severity'], name='aquacare_he_severit_7aeb12_idx'),
        ),
        migrations.AddIndex(
            model_name='communityreport',
            index=models.Index(fields=['village', 'status'], name='aquacare_co_village_4f464a_idx'),
        ),
    ]
